-- 3. List all the tables created
-- mandatory
-- Write a script that list all the tables in alx_book_store in your MySQL server.

-- The name of the file should be task_3.sql
-- The database name will be passed as argument of mysql command
-- Repo:

-- GitHub repository: Intro_to_DB
-- File: task_3.sql

SHOW TABLES IN alx_book_store;
-- The output will list all the tables created in the alx_book_store database.
-- The output will include:
-- +-------------------+
-- | Tables_in_alx_book_store |
-- +-------------------+
-- | Authors           |
-- | Books             |
-- | Customers         |
-- | Orders            |
-- | Order_Details     |
-- +-------------------+        
-- 5 rows in set (0.00 sec)
-- Note: The output may vary based on the actual tables created in the database.
---- Ensure that the alx_book_store database exists before running this command.
-- If the database does not exist, you will receive an error message indicating that the database does not exist.
-- Example error message:
-- ERROR 1049 (42000): Unknown database 'alx_book_store'    
-- This indicates that the database needs to be created first before listing the tables.    
-- Ensure that you have the necessary permissions to access the alx_book_store database and list its tables.
-- If you do not have the necessary permissions, you may receive an error message indicating that you do not have the required privileges to access the database.
-- Example error message:
-- ERROR 1044 (42000): Access denied for user 'your_user'@'     'localhost' to database 'alx_book_store'
-- This indicates that you need to check your user privileges and ensure that you have the necessary permissions to access the alx_book_store database.
-- If you have the necessary permissions and the database exists, the command will successfully list all the tables in the alx_book_store database.
-- The output
-- will include the names of all the tables created in the alx_book_store database, such as Authors, Books, Customers, Orders, and Order_Details.   
-- This command is useful for verifying the structure of the database and ensuring that all tables have been created successfully.
-- Ensure that the alx_book_store database exists before running this command.
-- If the database does not exist, you will receive an error message indicating that the database does
-- not exist.
-- Example error message:
-- ERROR 1049 (42000): Unknown database 'alx_book_store'        
-- This indicates that the database needs to be created first before listing the tables.
-- Ensure that you have the necessary permissions to access the alx_book_store database and list its        